-- Update handle_new_user to not generate wallet address directly
-- The wallet will be generated by the generate-user-wallet edge function
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  phone_num TEXT;
BEGIN
  -- Extract phone number from metadata
  phone_num := NEW.raw_user_meta_data->>'phone_number';
  
  -- Insert into profiles WITHOUT wallet_address (will be generated by edge function)
  INSERT INTO public.profiles (id, phone_number, email)
  VALUES (NEW.id, phone_num, NEW.email)
  ON CONFLICT (id) DO UPDATE
  SET phone_number = EXCLUDED.phone_number,
      email = EXCLUDED.email;
  
  -- Insert into user_registry WITHOUT wallet_address initially
  INSERT INTO public.user_registry (phone_number, user_id)
  VALUES (phone_num, NEW.id)
  ON CONFLICT (phone_number) DO UPDATE
  SET user_id = EXCLUDED.user_id;
  
  RETURN NEW;
END;
$function$;